version: '3'
services:
  game:
    container_name: game
    build:
      context: ..
      dockerfile: ./build/game/Dockerfile.dev
    env_file:
      - ../config/game.dev.env
    ports:
      - 3001:3001
      - 4000:4000
    volumes:
      - ..:/app
  mysql:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306